Document: nfs-screenshot
Title: Debian nfs-screenshot Manual
Author: <insert document author here>
Abstract: This manual describes what nfs-screenshot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/nfs-screenshot/nfs-screenshot.sgml.gz

Format: postscript
Files: /usr/share/doc/nfs-screenshot/nfs-screenshot.ps.gz

Format: text
Files: /usr/share/doc/nfs-screenshot/nfs-screenshot.text.gz

Format: HTML
Index: /usr/share/doc/nfs-screenshot/html/index.html
Files: /usr/share/doc/nfs-screenshot/html/*.html
